services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  node_modules:
