services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
